---
apiVersion: v1
kind: Secret
metadata:
  name: mi
  namespace: minio
  labels:
    app.kubernetes.io/name: mi
    app.kubernetes.io/instance: mi
type: Opaque
data:
  user: "admin" #min 8 symbols
  password: "password"  #min 8 symbols